.TH CONJUGAME 1
.SH NAME
conjugame \- show portuguese's verbs conjugations
.SH SYNOPSIS
.B conjugame
[\fIVerb(s)\fR]
.SH DESCRIPTION
Displays portuguese's verbs conjugations on terminal. Regular conjugation will be displayed in cyan,
while unregular conjugations will be shown in red.

Multiple accpetable conjugations will be displayed separeted by a slash(/)
.SH OPTIONS
.BR \fBVerb(s)\fR
  One or more verbs in infinitive form to be conjugated.
